version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  build-and-test:  
    docker:
      # Using a browser version here so I can test with Cypress
      - image: cimg/node:current-browsers
    steps:

      # Checkout the repo
      - checkout

      # Installs dependencies and caches them for later builds
      - node/install-packages

      # Runs the tests 
      - run:
          name: Run tests
          command: npm run test:nowatch
      
      # Runs the linter and makes sure it's not failing and doesn't have more than 5 warnings
      - run:
          name: Linting
          command: npm run lint:ci
      
      # Build the app and makes sure it doesn't exceed the max size
      - run:
          name: Size
          command: npm run size:ci

workflows:
  sample: 
    jobs:
      - build-and-test
